### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/code_execution/data/submission_format.csv'

### ISSUE THREAD

**Issue by johntiger1** [drivendataorg/visiomel-melanoma-runtime#25]
https://github.com/drivendataorg/visiomel-melanoma-runtime/blob/df507909360246bc5a8e0852dd2a08724e8c1a38/examples_src/benchmark/main.py#L34

Getting this error:
Traceback (most recent call last):
  File "/code_execution/main.py", line 61, in <module>
    main()
  File "/code_execution/main.py", line 34, in main
    submission_format = pd.read_csv(DATA_ROOT / "submission_format.csv", index_col=0)
  File "/opt/conda/envs/condaenv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/condaenv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/condaenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/condaenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/envs/condaenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/envs/condaenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/envs/condaenv/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/code_execution/data/submission_format.csv'
ERROR conda.cli.main_run:execute(47): `conda run python main.py` failed. (See above for error)

I am following the instructions from scratch, on a new machine:
```
make pull
make pack-submission
make test-submission
```

**Comment by johntiger1** [comment]
Nvm, needed to dig into the instructions to find:

```Start by downloading code_execution_development_data.tgz from the [data download page](https://www.drivendata.org/competitions/148/visiomel/data/). Unzip and extract the archive to data directory and you can develop and debug your submission on your local machine.```

I recommend changing the instructions to specify that these commands have an external dependency:

```
make pull
make pack-submission
make test-submission```

**Comment by ejm714** [comment]
Glad you found the details about the code execution test data! Feel free to submit a PR to the README with the clarification you'd recommend

**Comment by ejm714** [comment]
Going to close this issue since the FileNotFound error is due to a skipped pre-requisite. That said, we'd consider a PR to the README to make this setup clearer.
